package mockstorage

import (
	mock "github.com/stretchr/testify/mock"
	models "sadlil.com/samples/crud/pkg/storage/models"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Todo provides a mock function with given fields:
func (_m *Store) Todo() models.TodoQuery {
	return new(TodoQuery)
}

type mockConstructorTestingT interface {
	mock.TestingT
	Cleanup(func())
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStore(mockConstructorTestingT) *Store {
	mock := &Store{}
	return mock
}
