// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: crudapi.proto

package crudapiv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TodoStatus enum defines the possible states of a Todo object.
type TodoStatus int32

const (
	TodoStatus_TODO_STATUS_UNSPECIFIED TodoStatus = 0
	TodoStatus_TODO_STATUS_PENDING     TodoStatus = 1
	TodoStatus_TODO_STATUS_IN_PROGRESS TodoStatus = 2
	TodoStatus_TODO_STATUS_DONE        TodoStatus = 3
	TodoStatus_TODO_STATUS_DELETED     TodoStatus = 4
	TodoStatus_TODO_STATUS_ABANDONED   TodoStatus = 5
)

// Enum value maps for TodoStatus.
var (
	TodoStatus_name = map[int32]string{
		0: "TODO_STATUS_UNSPECIFIED",
		1: "TODO_STATUS_PENDING",
		2: "TODO_STATUS_IN_PROGRESS",
		3: "TODO_STATUS_DONE",
		4: "TODO_STATUS_DELETED",
		5: "TODO_STATUS_ABANDONED",
	}
	TodoStatus_value = map[string]int32{
		"TODO_STATUS_UNSPECIFIED": 0,
		"TODO_STATUS_PENDING":     1,
		"TODO_STATUS_IN_PROGRESS": 2,
		"TODO_STATUS_DONE":        3,
		"TODO_STATUS_DELETED":     4,
		"TODO_STATUS_ABANDONED":   5,
	}
)

func (x TodoStatus) Enum() *TodoStatus {
	p := new(TodoStatus)
	*p = x
	return p
}

func (x TodoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TodoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_crudapi_proto_enumTypes[0].Descriptor()
}

func (TodoStatus) Type() protoreflect.EnumType {
	return &file_crudapi_proto_enumTypes[0]
}

func (x TodoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TodoStatus.Descriptor instead.
func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{0}
}

// Todo message represents a Todo object.
type Todo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid uniquely represents any Todo object in the storage. The value of
	// id will be generated by the system while the todo is being crated.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User provided display name of the todo.
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// User defined priority of the TODO, can only be set a string value of P(0-4).
	Priority string `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	// Created at timestamp, represents when the entry is being created by the user.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// User defined deadline specified in duration, indicates the time by when the task
	// should be completed.
	Deadline *durationpb.Duration `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Status of the todo.
	Status        TodoStatus `protobuf:"varint,7,opt,name=status,proto3,enum=crudapi.v1.TodoStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_crudapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetDeadline() *durationpb.Duration {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Todo) GetStatus() TodoStatus {
	if x != nil {
		return x.Status
	}
	return TodoStatus_TODO_STATUS_UNSPECIFIED
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_crudapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_crudapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type ListTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        TodoStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=crudapi.v1.TodoStatus" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodoRequest) Reset() {
	*x = ListTodoRequest{}
	mi := &file_crudapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodoRequest) ProtoMessage() {}

func (x *ListTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodoRequest.ProtoReflect.Descriptor instead.
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{3}
}

func (x *ListTodoRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTodoRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTodoRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListTodoRequest) GetStatus() TodoStatus {
	if x != nil {
		return x.Status
	}
	return TodoStatus_TODO_STATUS_UNSPECIFIED
}

func (x *ListTodoRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type ListTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodoResponse) Reset() {
	*x = ListTodoResponse{}
	mi := &file_crudapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodoResponse) ProtoMessage() {}

func (x *ListTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodoResponse.ProtoReflect.Descriptor instead.
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{4}
}

func (x *ListTodoResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_crudapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoResponse) Reset() {
	*x = GetTodoResponse{}
	mi := &file_crudapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoResponse) ProtoMessage() {}

func (x *GetTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoResponse.ProtoReflect.Descriptor instead.
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{6}
}

func (x *GetTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       *Todo                  `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_crudapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTodoRequest) GetPayload() *Todo {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UpdateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoResponse) Reset() {
	*x = UpdateTodoResponse{}
	mi := &file_crudapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoResponse) ProtoMessage() {}

func (x *UpdateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_crudapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crudapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_crudapi_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_crudapi_proto protoreflect.FileDescriptor

const file_crudapi_proto_rawDesc = "" +
	"\n" +
	"\rcrudapi.proto\x12\n" +
	"crudapi.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xce\x02\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x18dR\x04name\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\vdescription\x125\n" +
	"\bpriority\x18\x04 \x01(\tB\x19\xfaB\x16r\x14R\x02P0R\x02P1R\x02P2R\x02P3R\x02P4R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\bdeadline\x18\x06 \x01(\v2\x19.google.protobuf.DurationB\b\xfaB\x05\xaa\x01\x02\b\x01R\bdeadline\x128\n" +
	"\x06status\x18\a \x01(\x0e2\x16.crudapi.v1.TodoStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\"C\n" +
	"\x11CreateTodoRequest\x12.\n" +
	"\x04todo\x18\x01 \x01(\v2\x10.crudapi.v1.TodoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04todo\":\n" +
	"\x12CreateTodoResponse\x12$\n" +
	"\x04todo\x18\x01 \x01(\v2\x10.crudapi.v1.TodoR\x04todo\"\xaa\x01\n" +
	"\x0fListTodoRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.crudapi.v1.TodoStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\":\n" +
	"\x10ListTodoResponse\x12&\n" +
	"\x05todos\x18\x01 \x03(\v2\x10.crudapi.v1.TodoR\x05todos\")\n" +
	"\x0eGetTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"7\n" +
	"\x0fGetTodoResponse\x12$\n" +
	"\x04todo\x18\x01 \x01(\v2\x10.crudapi.v1.TodoR\x04todo\"b\n" +
	"\x11UpdateTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x124\n" +
	"\apayload\x18\x02 \x01(\v2\x10.crudapi.v1.TodoB\b\xfaB\x05\x8a\x01\x02\x10\x01R\apayload\":\n" +
	"\x12UpdateTodoResponse\x12$\n" +
	"\x04todo\x18\x01 \x01(\v2\x10.crudapi.v1.TodoR\x04todo\",\n" +
	"\x11DeleteTodoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id*\xa9\x01\n" +
	"\n" +
	"TodoStatus\x12\x1b\n" +
	"\x17TODO_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TODO_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17TODO_STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10TODO_STATUS_DONE\x10\x03\x12\x17\n" +
	"\x13TODO_STATUS_DELETED\x10\x04\x12\x19\n" +
	"\x15TODO_STATUS_ABANDONED\x10\x052\xfa\x03\n" +
	"\vTodoService\x12d\n" +
	"\n" +
	"CreateTodo\x12\x1d.crudapi.v1.CreateTodoRequest\x1a\x1e.crudapi.v1.CreateTodoResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/todo\x12[\n" +
	"\bListTodo\x12\x1b.crudapi.v1.ListTodoRequest\x1a\x1c.crudapi.v1.ListTodoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/todo\x12]\n" +
	"\aGetTodo\x12\x1a.crudapi.v1.GetTodoRequest\x1a\x1b.crudapi.v1.GetTodoResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/todo/{id}\x12i\n" +
	"\n" +
	"UpdateTodo\x12\x1d.crudapi.v1.UpdateTodoRequest\x1a\x1e.crudapi.v1.UpdateTodoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/todo/{id}\x12^\n" +
	"\n" +
	"DeleteTodo\x12\x1d.crudapi.v1.DeleteTodoRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/todo/{id}B\xd2\x02\x92A\xa2\x01\x12.\n" +
	"\x10Sample CRUD APIs\"\x12\x1a\x10kzirtm@gmail.com2\x06v0.1.0\x1a\x15http://localhost:6999*\x01\x012\x10application/json:\x10application/jsonr2\x120https://github.com/sadlil/samples/tree/main/crud\n" +
	"\x0ecom.crudapi.v1B\fCrudapiProtoH\x02P\x01ZAgithub.com/sadlil/system-samples/crud/apis/go/crudapipb;crudapiv1\xa2\x02\x03CXX\xaa\x02\n" +
	"Crudapi.V1\xca\x02\n" +
	"Crudapi\\V1\xe2\x02\x16Crudapi\\V1\\GPBMetadata\xea\x02\vCrudapi::V1b\x06proto3"

var (
	file_crudapi_proto_rawDescOnce sync.Once
	file_crudapi_proto_rawDescData []byte
)

func file_crudapi_proto_rawDescGZIP() []byte {
	file_crudapi_proto_rawDescOnce.Do(func() {
		file_crudapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crudapi_proto_rawDesc), len(file_crudapi_proto_rawDesc)))
	})
	return file_crudapi_proto_rawDescData
}

var file_crudapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crudapi_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_crudapi_proto_goTypes = []any{
	(TodoStatus)(0),               // 0: crudapi.v1.TodoStatus
	(*Todo)(nil),                  // 1: crudapi.v1.Todo
	(*CreateTodoRequest)(nil),     // 2: crudapi.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),    // 3: crudapi.v1.CreateTodoResponse
	(*ListTodoRequest)(nil),       // 4: crudapi.v1.ListTodoRequest
	(*ListTodoResponse)(nil),      // 5: crudapi.v1.ListTodoResponse
	(*GetTodoRequest)(nil),        // 6: crudapi.v1.GetTodoRequest
	(*GetTodoResponse)(nil),       // 7: crudapi.v1.GetTodoResponse
	(*UpdateTodoRequest)(nil),     // 8: crudapi.v1.UpdateTodoRequest
	(*UpdateTodoResponse)(nil),    // 9: crudapi.v1.UpdateTodoResponse
	(*DeleteTodoRequest)(nil),     // 10: crudapi.v1.DeleteTodoRequest
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_crudapi_proto_depIdxs = []int32{
	11, // 0: crudapi.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: crudapi.v1.Todo.deadline:type_name -> google.protobuf.Duration
	0,  // 2: crudapi.v1.Todo.status:type_name -> crudapi.v1.TodoStatus
	1,  // 3: crudapi.v1.CreateTodoRequest.todo:type_name -> crudapi.v1.Todo
	1,  // 4: crudapi.v1.CreateTodoResponse.todo:type_name -> crudapi.v1.Todo
	0,  // 5: crudapi.v1.ListTodoRequest.status:type_name -> crudapi.v1.TodoStatus
	1,  // 6: crudapi.v1.ListTodoResponse.todos:type_name -> crudapi.v1.Todo
	1,  // 7: crudapi.v1.GetTodoResponse.todo:type_name -> crudapi.v1.Todo
	1,  // 8: crudapi.v1.UpdateTodoRequest.payload:type_name -> crudapi.v1.Todo
	1,  // 9: crudapi.v1.UpdateTodoResponse.todo:type_name -> crudapi.v1.Todo
	2,  // 10: crudapi.v1.TodoService.CreateTodo:input_type -> crudapi.v1.CreateTodoRequest
	4,  // 11: crudapi.v1.TodoService.ListTodo:input_type -> crudapi.v1.ListTodoRequest
	6,  // 12: crudapi.v1.TodoService.GetTodo:input_type -> crudapi.v1.GetTodoRequest
	8,  // 13: crudapi.v1.TodoService.UpdateTodo:input_type -> crudapi.v1.UpdateTodoRequest
	10, // 14: crudapi.v1.TodoService.DeleteTodo:input_type -> crudapi.v1.DeleteTodoRequest
	3,  // 15: crudapi.v1.TodoService.CreateTodo:output_type -> crudapi.v1.CreateTodoResponse
	5,  // 16: crudapi.v1.TodoService.ListTodo:output_type -> crudapi.v1.ListTodoResponse
	7,  // 17: crudapi.v1.TodoService.GetTodo:output_type -> crudapi.v1.GetTodoResponse
	9,  // 18: crudapi.v1.TodoService.UpdateTodo:output_type -> crudapi.v1.UpdateTodoResponse
	13, // 19: crudapi.v1.TodoService.DeleteTodo:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_crudapi_proto_init() }
func file_crudapi_proto_init() {
	if File_crudapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crudapi_proto_rawDesc), len(file_crudapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crudapi_proto_goTypes,
		DependencyIndexes: file_crudapi_proto_depIdxs,
		EnumInfos:         file_crudapi_proto_enumTypes,
		MessageInfos:      file_crudapi_proto_msgTypes,
	}.Build()
	File_crudapi_proto = out.File
	file_crudapi_proto_goTypes = nil
	file_crudapi_proto_depIdxs = nil
}
