development:
  dialect: sqlite3
  datasource: /tmp/samples/crud/todo.db
  dir: /tmp/samples/crud
test:
  dialect: mysql
  datasource: root:Y80mmmUhR4@tcp(localhost:3106)/todo_service?parseTime=true
  dir: .
